//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJ.WCF.ConsoleApp.ServiceReferencePessoaApp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://schemas.datacontract.org/2004/07/NJ.WCF.Host.Entidades")]
    [System.SerializableAttribute()]
    public partial class Pessoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePessoaApp.IPessoaApp")]
    public interface IPessoaApp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPessoaApp/ListarPessoas", ReplyAction="http://tempuri.org/IPessoaApp/ListarPessoasResponse")]
        NJ.WCF.ConsoleApp.ServiceReferencePessoaApp.Pessoa[] ListarPessoas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPessoaApp/ListarPessoas", ReplyAction="http://tempuri.org/IPessoaApp/ListarPessoasResponse")]
        System.Threading.Tasks.Task<NJ.WCF.ConsoleApp.ServiceReferencePessoaApp.Pessoa[]> ListarPessoasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPessoaAppChannel : NJ.WCF.ConsoleApp.ServiceReferencePessoaApp.IPessoaApp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PessoaAppClient : System.ServiceModel.ClientBase<NJ.WCF.ConsoleApp.ServiceReferencePessoaApp.IPessoaApp>, NJ.WCF.ConsoleApp.ServiceReferencePessoaApp.IPessoaApp {
        
        public PessoaAppClient() {
        }
        
        public PessoaAppClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PessoaAppClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PessoaAppClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PessoaAppClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NJ.WCF.ConsoleApp.ServiceReferencePessoaApp.Pessoa[] ListarPessoas() {
            return base.Channel.ListarPessoas();
        }
        
        public System.Threading.Tasks.Task<NJ.WCF.ConsoleApp.ServiceReferencePessoaApp.Pessoa[]> ListarPessoasAsync() {
            return base.Channel.ListarPessoasAsync();
        }
    }
}
